# Generated by Django 4.2 on 2023-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('cooking_time', models.CharField(max_length=10)),
                ('difficulty', models.CharField(max_length=50)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('recipe_type', models.CharField(choices=[('Breakfast', 'Breakfasts'), ('Lunch', 'Lunches'), ('Dinner', 'Dinners')], default='Breakfast', max_length=10)),
            ],
        ),
    ]
